config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'devise/sessions'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resource :like, only: :create
    end
  end
  delete '/users/:user_id/posts/:post_id/comments/:id', to: 'comments#destroy', as: :destroy_user_post_comment
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

    return unless user.present?

    can :manage, User, id: user.id
    can :manage, Post, author_id: user.id
    can :create, Comment
    can :destroy, Comment, author_id: user.id
    can :create, Like

    return unless user.role == 'admin'

    can :manage, :all
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :comments_update

  private

  def comments_update
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_save :likes_update

  private

  def likes_update
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, class_name: 'Like', dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts

  def display_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: %i[index show]

  protected

  def configure_permitted_parameters
    attributes = [:name]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(current_user, @post), notice: 'Comment was successfully created.'
    else
      render 'posts/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to user_post_path(@comment.post.author, @comment.post), notice: 'Comment was successfully removed.'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(author: current_user)

    if @like.save
      redirect_to user_post_path(current_user, @post), notice: 'Like was successfully added.'
    else
      redirect_to user_post_path(current_user, @post), alert: 'Failed to add like.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @all_posts = @user.posts.includes(:author, comments: :author).order(created_at: :desc).paginate(page: params[:page], per_page: 5)
  end

  def show
    @post = Post.includes(:author).find(params[:id])
    @comment = Comment.new
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.author = current_user

    if @post.destroy
      redirect_to user_path(@user), notice: 'Post was successfully deleted.'
    else
      redirect_to user_post_path(@user, @post), alert: 'Post was not deleted.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @individual_post = User.find(params[:id])
    @posts = Post.where(author_id: params[:id])
    @post = @individual_post.posts.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
 <div>
    <%= form_with(model: @comment, url: user_post_comments_path(@post.author, @post)) do |form| %>
      <%= form.label :text %>
      <%= form.text_area :text, class: "comment-textarea" %>

      <%= form.submit 'Create Comment', class: "comment-submit-button" %>
    <% end %>
  </div>

app/views/comments/new.html.erb
 <%= render 'comments/comment', post: @post%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, url: user_posts_path(@post&.author), method: :post, class: "form-container") do |form| %>
  <div class="form-field">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-input" %>
  </div>

  <div class="form-field">
    <%= form.label :text, class: "form-label" %>
    <%= form.text_area :text, class: "form-textarea" %>
  </div>

  <%= form.submit 'Create Post', class: "form-submit-button" %>
<% end %>

app/views/posts/index.html.erb
<div class="user-posts">
  <h1 class="user-header">
    <%= image_tag(@user.photo) %>
    <%= @user.name %>
  </h1>
  <% @all_posts.each do |post| %>
    <div class="post-card">
      <%= link_to user_post_path(@user, post) do %>
        <h2 class="post-title"><%= post.title %></h2>
        <p class="post-text"><%= post.text %></p>
        <p class="post-likes">Likes: <%= post.likes_counter %></p>
        <p class="post-comments">Comments: <%= post.comments_counter %></p>
        <h3 class="comments-heading">Comments:</h3>
        <ul class="comments-list">
          <% post.display_comments.each do |comment| %>
            <li>
              <%= comment.author.name %> : <%= comment.text %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  <% end %>
  <div class="pagination-button">
    <%= will_paginate @all_posts %>
  </div>
  <div class="back-button">
    <%= link_to 'Back to User', user_path(@user) %>
  </div>
</div>

app/views/posts/new.html.erb
<%= form_with(model: @post, url: user_posts_path(@user)) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :text %>
  <%= form.text_area :text %>

  <%= form.submit 'Create Post' %>
<% end %>

app/views/posts/show.html.erb
<div class="post-details">
  <div class="post-info">
    <h2 class="post-title"><%= @post.title %></h2>
    <p class="post-likes">Likes: <%= @post.likes_counter %></p>
    <p class="post-comments">Comments: <%= @post.comments_counter %></p>
    <p class="post-text"><%= @post.text %></p>
  </div>
</div>

<div class="delete-post-button">
  <%= form_with(model: [@post.author, @post], method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }) do |form| %>
    <%= form.submit 'Delete Post' %>
  <% end %>
</div>


<div class='likr'>
  <%= button_to 'Like Post', user_post_like_path(@post.author, @post), method: :post, class: "liker" %>
</div>

<div class="comments-section">
  <h3 class="comments-heading">Comments:</h3>
  <ul class="comments-list">
    <% @post.comments.each do |comment| %>
      <li>
        <span class="comment-author"><%= comment.author.name %></span>
        : <%= comment.text %>
        <% if can? :destroy, comment %>
          <%= form_with(model: [comment.author, @post, comment], method: :delete, data: { confirm: 'Are you sure you want to remove this comment?' }) do |form| %>
            <%= form.submit 'Remove' %>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div>
    <%= link_to 'Leave a Comment', new_user_post_comment_path(@post.author, @post), class: "comment-button" %>
  </div>
</div>

<div class="back-button">
  <%= link_to 'Back to Posts', user_posts_path(@post.author) %>
</div>

app/views/users/_user.html.erb
<li class='individual-user'>
  <% if user.photo.present? %>
    <span class='user-image'><%= image_tag user.photo %></span>
  <% else %>
    <span class='user-image'><%= image_tag 'https://rb.gy/h3s8k' %></span>
  <% end %>
  <span class='user-name'><%= link_to user.name, user %></span>
  <span class='particulars'>Number of posts: <%= user.posts_counter %></span>
</li>

app/views/users/index.html.erb
<% if user_signed_in? %>
 <div> Welcome <%= current_user.email %> </div>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= button_to "Sign in", new_user_session_path %>
<% end %>

<h1 class="styled-heading">All Users</h1>
<div class="all-users">
  <ul>
    <%=render partial: 'user',collection:@users %>
  </ul>
</div>

app/views/users/show.html.erb
<div class="post-details">
  <div class="post-header">
    <span class="post-image">
      <%= image_tag(@individual_post.photo) %>
    </span>
    <h1 class="post-title"><%= @individual_post.name %></h1>
    <p class="post-counter">Number of posts: <%= @individual_post.posts_counter %></p>
  </div>
  <div class="post-bio">
    <h3>Bio</h3>
    <p><%= @individual_post.bio %></p>
  </div>
  <div class="post-list">
    <% @individual_post.most_recent_posts.each do |post| %>
      <div class="post-card">
        <%= link_to user_post_path(@individual_post, post.id) do %>
          <h3 class="post-heading"><%= post.title %></h3>
          <p class="post-text"><%= truncate(post.text, length: 11, omission: '...') %></p>
          <p class="post-comments">Comments: <%= post.comments_counter %></p>
          <p class="post-likes">Likes: <%= post.likes_counter %></p>
          <div>
          <%if can? :destroy, post %>
            <%= link_to 'Delete Post', user_post_path(@individual_post, post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' } %>
          <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div>
    <%= link_to 'Add Post', new_user_post_path(@individual_post), class: "add-post-button" %>
  </div>

  <button class="see-all-button">
    <%= link_to 'See All', user_posts_path(@individual_post) %>
  </button>
  <div class="back-button">
    <%= link_to 'Back to Users', users_path %>
  </div>
</div>